@echo off
echo Creating virtual environment...
python -m venv myenv
echo Activating virtual environment...
myenv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Setup complete.